### ISSUE TITLE
Monadic quasiquoter

### ISSUE THREAD

**Issue by 0xd34df00d** [sol/interpolate#15]
How do you reckon having an `im` quasiquoter such that `[im|#{foo} #{bar}|]` produces `Monad m => m String` (and similarly for the `.IsString` version) and where `foo` can be either of any type `t` that's accepted now (that is, `String` and something that can be `Show`ed) as well as `m t`?

The motivation is that right now I'm writing a lot of code along the lines of
```haskell
compileTerm :: MonadReader Context m => Term -> m String
compileTerm (TBinOp t1 op t2) = do
  s1 <- compileTerm t1
  s2 <- compileTerm t2
  pure [i|#{s1} #{compileOp op} #{s2}|]
```
while I'd like it to be like
```haskell
compileTerm (TBinOp t1 op t2) = [im|#{compileTerm t1} #{compileOp op} #{compileTerm t2}|]
```

If this is a direction you consider in line with how you see your library, I'd be happy to take a stab at this. Naming is discussible, of course, `im` is just something I came up with for "<strong>i</strong>nterpolate in a <strong>m</strong>onad".

**Comment by sol** [comment]
How about adding support for holes instead?  That way your use case could be achieved with:

```haskell
compileTerm (TBinOp t1 op t2) = [i|#{} #{compileOp op} #{}|] <$> compileTerm t1 <*> compileTerm t2
```

**Comment by sol** [comment]
https://github.com/sol/interpolate/pull/16

**Comment by sol** [comment]
On Hackage as `0.2.1`.
