### ISSUE TITLE
Multiline strings on Windows end up with Windows line endings

### ISSUE THREAD

**Issue by thomasjm** [sol/interpolate#9]
If I have a string constant like

```
multiline :: String
multiline = [i|line 1
line 2
line 3|]
```

then it ends up having `\r\n` line endings:

```
-> multiline
"line 1\r\nline 2\r\nline 3"
```

This is a bit surprising and probably the wrong thing to do given that almost all Haskell libraries convert to normal `\n` endings when dealing with Windows (like `readFile` etc.).

In my case it causes confusion in tests, for example:

```
multilineConstant <- [i|
...
|]

unitTests = testSpec "(checked by Hspec)" $ do
  it "checks some output is valid" $ do
    result <- doSomething
    -- when everything else behaves properly, result has \n newlines but multilineConstant has \r\n
    result `shouldBe` multilineConstant 
```

**Comment by sol** [comment]
@thomasjm good catch.  I guess we want to address this in `interpolate`, even though by now I think this should be fixed in GHC itself (there are similar issues with Haddock comments).

**Comment by thomasjm** [comment]
I'm on stack `lts-10.0` (GHC 8.2.2) FWIW.

**Comment by sol** [comment]
For reference https://ghc.haskell.org/trac/ghc/ticket/14876
